
package com.opendevup.client;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.springframework.beans.factory.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BibliotequeWS", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BibliotequeWS {


    /**
     * 
     * @return
     *     returns java.util.List<client.Livre>
     */
    @WebMethod(operationName = "Liste des livres")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Liste des livres", targetNamespace = "http://service/", className = "client.Liste_0020Des_0020Livres")
    @ResponseWrapper(localName = "Liste des livresResponse", targetNamespace = "http://service/", className = "client.Liste_0020Des_0020LivresResponse")
    @Action(input = "http://service/BibliotequeWS/Liste des livresRequest", output = "http://service/BibliotequeWS/Liste des livresResponse")
    public List<Livre> liste_0020Des_0020Livres();

    /**
     * 
     * @param titre
     * @param nom_0020D_0027Utilisateur
     */
    @WebMethod
    @RequestWrapper(localName = "pret", targetNamespace = "http://service/", className = "client.Pret")
    @ResponseWrapper(localName = "pretResponse", targetNamespace = "http://service/", className = "client.PretResponse")
    @Action(input = "http://service/BibliotequeWS/pretRequest", output = "http://service/BibliotequeWS/pretResponse")
    public void pret(
        @WebParam(name = "titre", targetNamespace = "")
        String titre,
        @WebParam(name = "Nom d'utilisateur", targetNamespace = "")
        String nom_0020D_0027Utilisateur);

    /**
     * 
     * @param date_0020De_0020Naissance
     * @param motdepasse
     * @param nom
     * @param prenom
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "inscription", targetNamespace = "http://service/", className = "client.Inscription")
    @ResponseWrapper(localName = "inscriptionResponse", targetNamespace = "http://service/", className = "client.InscriptionResponse")
    @Action(input = "http://service/BibliotequeWS/inscriptionRequest", output = "http://service/BibliotequeWS/inscriptionResponse")
    public void inscription(
        @WebParam(name = "nom", targetNamespace = "")
        String nom,
        @WebParam(name = "prenom", targetNamespace = "")
        String prenom,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "motdepasse", targetNamespace = "")
        String motdepasse,
        @WebParam(name = "date de naissance", targetNamespace = "")
        XMLGregorianCalendar date_0020De_0020Naissance);

    /**
     * 
     * @param motdepasse
     * @param email
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "connexion", targetNamespace = "http://service/", className = "client.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://service/", className = "client.ConnexionResponse")
    @Action(input = "http://service/BibliotequeWS/connexionRequest", output = "http://service/BibliotequeWS/connexionResponse")
    public boolean connexion(
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "motdepasse", targetNamespace = "")
        String motdepasse);

}
