
package com.opendevup.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LivreServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8585/Bibliotheque?wsdl")
public class LivreServiceService
    extends Service
{

    private final static URL LIVRESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LIVRESERVICESERVICE_EXCEPTION;
    private final static QName LIVRESERVICESERVICE_QNAME = new QName("http://service/", "LivreServiceService");
    
  

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8585/Bibliotheque?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIVRESERVICESERVICE_WSDL_LOCATION = url;
        LIVRESERVICESERVICE_EXCEPTION = e;
    }

    public LivreServiceService() {
        super(__getWsdlLocation(), LIVRESERVICESERVICE_QNAME);
    }

    public LivreServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIVRESERVICESERVICE_QNAME, features);
    }

    public LivreServiceService(URL wsdlLocation) {
        super(wsdlLocation, LIVRESERVICESERVICE_QNAME);
    }

    public LivreServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIVRESERVICESERVICE_QNAME, features);
    }

    public LivreServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LivreServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BibliotequeWS
     */
    @WebEndpoint(name = "BibliotequeWSPort")
    public BibliotequeWS getBibliotequeWSPort() {
        return super.getPort(new QName("http://service/", "BibliotequeWSPort"), BibliotequeWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BibliotequeWS
     */
    @WebEndpoint(name = "BibliotequeWSPort")
    public BibliotequeWS getBibliotequeWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "BibliotequeWSPort"), BibliotequeWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIVRESERVICESERVICE_EXCEPTION!= null) {
            throw LIVRESERVICESERVICE_EXCEPTION;
        }
        return LIVRESERVICESERVICE_WSDL_LOCATION;
    }

}
